if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/conanbuildinfo.cmake")
    message(STATUS "Detected Conan build: perform conan setup")
    include("${CMAKE_CURRENT_SOURCE_DIR}/conanbuildinfo.cmake")
    # See: https://docs.conan.io/en/latest/howtos/manage_shared_libraries/rpaths.html#default-conan-approach
    if(APPLE)
        conan_basic_setup(KEEP_RPATHS)
    else()
        conan_basic_setup()
    endif()
endif()